#!/bin/sh
#
# Set the system time to the build time.
#

start() {
	/bin/date -u -s"`cat /etc/buildtime`" > /dev/null
}

case "$1" in
  start)
  	start
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
